version: '3'
services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/etc/timezone:/etc/timezone:ro'
    restart: always
    environment:
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_ROLLING_RESTART: "true"
      WATCHTOWER_SCHEDULE: "0 30 6 * * WED"
      WATCHTOWER_LABEL_ENABLE: "true"
    network_mode: bridge
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  default:
    name: bridge
    external: true
